# Generated by Django 6.0.5 on 2026-05-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='jefesoporte',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='legajo',
        ),
    ]
