# Generated by Django 6.0.5 on 2026-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jefesoporte',
            name='empresa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jefesoporte',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='soporte',
            name='empresa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='soporte',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
