# Generated by Django 6.0.5 on 2026-05-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cliente_nombre_jefesoporte_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='jefesoporte',
            old_name='nombre',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='soporte',
            old_name='nombre',
            new_name='username',
        ),
    ]
